export class InvoicesFakeDb
{
    public static invoices = [
        {
            "id": 1,
            "nameOfSupplier": "Supplier 1",
            "invoiceDate": "2018-10-18T13:22:31.653Z",
            "invoiceNumber": "INV23563",
            "manufacturerId": 1,
            "manufacturer": "Nippon",
            "manufacturersAddress": "Belgium",
            "supplierName": "Edhalsthel",
            "supplierAddrs": "Ethopia",
            "poNumberId": 2,
            "poNumber": 63253,
            "poDate": "2018-05-20T13:22:31.653Z",
            "challanId": 2,
            "challanNumber": 25,
            "challanDate": "2018-05-25T13:22:31.653Z",
            "productDetails": [
              {
                "id":1,
                "product": "Check 1",
                "quantity": 20,
                "unitId": 1,
                "unitName": "kgs",
                "unitPrice": 25,
                "totalPrice": 500,
                "vat": 20,
                "tax": 30,
              },
              {
                "id":2,
                "product": "Check 2",
                "quantity": 20,
                "unitId": 1,
                "unitName": "kgs",
                "unitPrice": 25,
                "totalPrice": 500,
                "vat": 20,
                "tax": 30,
              }
            ],
            "grandTotal": 500, 
            "totalVat": 20,
            "totalTax": 30,
            "advancePayment": 300,
            "totalPayable": 250,
            "amountInWords": "Two Hundred Fifty",
            "preparedBy": "Gokul",
            "designation": "SE",
            "status": "Approved"
          },
        {
            "id":2,
            "nameOfSupplier": "Supplier 2",
            "invoiceDate": "2018-10-18T13:22:31.653Z",
            "invoiceNumber": "INV41526",
            "manufacturerId": 2,
            "manufacturer": "Chewrolet",
            "manufacturersAddress": "America",
            "supplierName": "Sony",
            "supplierAddrs": "Japan",
            "poNumberId": 1,
            "poNumber": 25369,
            "poDate": "2018-10-18T13:22:31.653Z",
            "challanId": 1,
            "challanNumber": 35,
            "challanDate": "2018-12-30T13:22:31.653Z",
            "productDetails": [
              {
                "id":2,
                "product": "Check 2",
                "quantity": 35,
                "unitId":2, 
                "unitName": "litres",
                "unitPrice": 20,
                "totalPrice": 700,
                "vat": 30,
                "tax": 60,
              }
            ],
            "grandTotal": 700, 
            "totalVat": 30,
            "totalTax": 60,
            "advancePayment": 400,
            "totalPayable": 390,
            "amountInWords": "Three Hundred Ninety",
            "preparedBy": "Rishi",
            "designation": "TechLead",
            "status": "Approved"
          }
    ];
}
